In [ ]:
pip install numpy

In [ ]:
import numpy
arr=numpy.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np
print(np.__version__)

1.26.4


In [5]:
# The array object in NumPy is called ndarray.
import numpy as np 
arr=np.array([1,2,4,5,6,7,6])
print(arr)
print(type(arr))

[1 2 4 5 6 7 6]
<class 'numpy.ndarray'>


In [27]:
import numpy as np
arr=np.array((1,2,4,5,6,6,"Hello"))
print(arr)
print(type(arr))

['1' '2' '4' '5' '6' '6' 'Hello']
<class 'numpy.ndarray'>


In [30]:
# 2-D array
import numpy as np 
arr=np.array([[1,2,4,5],[2,4,7,8],[1,2,4,5]])
print(arr)

<class 'SyntaxError'>: closing parenthesis ')' does not match opening parenthesis '[' (<ipython-input-30-17679aa643bf>, line 3)

In [11]:
import numpy as np
arr=np.array([[1,2,4],[1,2,3],[12,3,5]])
print(arr)

[[ 1  2  4]
 [ 1  2  3]
 [12  3  5]]


In [12]:
import numpy as np
arr1=np.array([1,2,4,5])
arr2=np.array([2,4,6,7])
print(arr1+arr2)

[ 3  6 10 12]


In [13]:
# print even numbers present in a given array
import numpy as np
arr=np.array([1,2,34,4,5,6])
even_number=arr[arr%2==0]
print(even_number)

[ 2 34  4  6]


In [15]:
# add 2-D array
import numpy as np 
arr1=np.array([[1,2,3],[1,2,3]])
arr2=np.array([[1,2,3],[1,2,3]])
print(arr1+arr2)

[[2 4 6]
 [2 4 6]]


In [34]:
# Indexing in array
import numpy as np 
arr=np.array([1,2,4,5])
print(arr[0])
print(arr[-1])

1
5


In [18]:
# Access the element on the first row, second column:
import numpy as np 
arr=np.array([[1,2,3,5,4],[1,2,3,4,5]])
print(arr[0,1])

2


In [22]:
# Access the element on the second row, 5th column:
import numpy as np 
arr=np.array([[1,2,3,5,4],[1,2,3,4,5]])
print(arr[1,4])

5


In [23]:
# Print the last element from the 2nd dim:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [26]:
# Slicing in python means taking elements from one given index to another given index.

# We pass slice instead of index like this: [start:end].
import numpy as np
arr=np.array([1,2,3,4,5,5])
print(arr[1:3])

[2 3]


In [29]:
import numpy as np
arr=np.array([[1,2,3,4],[1,2,3,4]])
print(arr)

[[1 2 3 4]
 [1 2 3 4]]


In [33]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([1,2,3,4])
print(arr1+arr2)
arr3=np.array([[1,2,3,4],[1,2,3,4]])
arr4=np.array([[1,2,3,4],[1,2,3,4]])
print(arr3+arr4)
arr5=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
arr6=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(arr5+arr6)

[2 4 6 8]
[[2 4 6 8]
 [2 4 6 8]]
[[2 4 6 8]
 [2 4 6 8]
 [2 4 6 8]]
